### PR TITLE
Don't depth test fullscreen quad

### PR DESCRIPTION
**Pull request by TheoBerlin**
The fullscreen quad used when applying light to the backbuffer was being written to the depth buffer, causing particles to constantly be culled by the depth test.

Also had to tweak renderpass settings, so the depth buffer was loaded for the light pass.

### CODE REVIEW

**Comment by Mumsfilibaba** [comment]
Needs to use the depthbuffer from the GBuffer to be fully correct

**Comment by TheoBerlin** [comment]
How is the depth buffer needed, for reading or writing? Again, this change applies to the light pass, not the geometry pass. There is no need to test or write a fullscreen quad to the depth buffer.

**Comment by Mumsfilibaba** [comment]
It should be used when drawing the particles. Otherwise the particles will be drawn on top of all the other geometry and not taking into account if they are behind or in front of what's been drawn in the geometry pass.

**Comment by TheoBerlin** [comment]
This pull enabled reading from the depth buffer when drawing particles.

What the pull disables is reading and writing to the depth buffer when drawing the fullscreen quad when applying light to the scene.

EDIT: Only enabled reading from the depth buffer when drawing particles, typo.

**Pull request merged**
